version: 2
jobs:
  publish:
    docker:
      - image: eu.gcr.io/swade1987/kubernetes-toolkit:1.17.2
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.17
      - run:
          name: Install docker
          command: make install-docker
      - run:
          name: Install trivy
          command: |
            apk add --update-cache --upgrade --update curl
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - run:
          name: build docker image
          command: make build
      - run:
          name: Trivy scan
          command: make scan
      - run:
          name: Configure Digital Ocean
          command: make install-doctl-linux
      - run:
          name: Push Image to Digital Ocean
          command: make push-to-digitalocean
  scan:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: apk add --update alpine-sdk
      - run:
          name: Install trivy
          command: |
            apk add --update-cache --upgrade curl rpm
            VERSION=$(
                curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | \
                grep '"tag_name":' | \
                sed -E 's/.*"v([^"]+)".*/\1/'
            )
            wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
            tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
            mv trivy /usr/local/bin
      - run:
          name: trivy scan
          command: make scan
workflows:
  version: 2
  flow:
    jobs:
      - publish:
          filters:
            branches:
              only:
                - main